{% set name = "pygsl" %}
{% set version = "2.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pygsl/pygsl/archive/refs/tags/v.{{ version }}.tar.gz
  sha256: 9617c70ba63a0f936d44fecb2f779c46da7ac9c5793524f71eb483bb5ec01931

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 3
  skip: true  # [win or py<38]

requirements:
  build:
    - python
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython
    - libcblas
    - setuptools
    - wheel
    - numpy >=2.0    # [py>=313]
    - numpy <2.0     # [py<313]
    - pip
  run:
    - python
    - numpy >=2.0    # [py>=313]
    - numpy <2.0     # [py<313]

test:
  imports:
    - pygsl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pygsl/pygsl
  summary: pygsl - GNU Scientific Library Interface
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - steffengraber
