{% set name = "pygsl" %}
{% set version = "2.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pygsl/pygsl/releases/download/v{{ version }}/pygsl-{{ version }}.tar.gz
  sha256: 88082cd00de8dab901ca79f59ab702b2c984232ab11b5ff2426716965168e2c8

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  skip: true  # [win or py<39]
  run_exports:
    # This ensures that packages that depend on 'gsl' automatically get
    # the GSL runtime libraries.
    - {{ pin_compatible('gsl') }}

requirements:
  build:
    - python
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - pkg-config
  host:
    - python
    - cython
    - libcblas
    - setuptools
    - swig
    - wheel
    - numpy >=1.8.2
    - pip
    - gsl
    - meson-python
  run:
    - python
    - gsl
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pygsl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pygsl/pygsl
  summary: pygsl - GNU Scientific Library Interface
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - steffengraber
