{% set name = "pygsl" %}
{% set version = "2.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pygsl/pygsl/releases/download/v{{ version }}/pygsl-{{ version }}.tar.gz
  sha256: 8422547e0cddda555aee2f81fb821918c90cf3009a2c05ad34178e4377c483b0

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [win or py<39]
  run_exports:
    # This ensures that packages that depend on 'gsl' automatically get
    # the GSL runtime libraries.
    - {{ pin_compatible('gsl') }}

requirements:
  build:
    - python
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - swig
    - gsl
    - make
    - cmake
    - pkg-config
  host:
    - python
    - swig
    - pkg-config
    - gsl
    - numpy >=1.8.2
    - pip
  run:
    - python
    - gsl
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pygsl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pygsl/pygsl
  summary: pygsl - GNU Scientific Library Interface
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - steffengraber
