{% set name = "pygsl" %}
{% set version = "2.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pygsl/pygsl/releases/download/v{{ version }}/pygsl-{{ version }}.tar.gz
  sha256: 8422547e0cddda555aee2f81fb821918c90cf3009a2c05ad34178e4377c483b0
  patches:
    - patches/0001-fix-msvc-variadic-debug-macro.patch
    - patches/0002-drop-gsl-var-from-swig-interpolation-decls.patch
    - patches/0003-fix-msvc-pointer-arithmetic-and-uint.patch
    - patches/0004-fix-msvc-gsl-data-symbol-imports.patch

build:
  number: 4
  skip: true  # [py<39]
  script: |
    meson setup builddir --prefix=$PREFIX # [unix]
    meson compile -C builddir # [unix]
    meson install -C builddir # [unix]

requirements:
  build:
    - python
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - swig
    - make
    - cmake
    - pkg-config
    - meson
    - ninja
    - setuptools
    - numpy {{ numpy }}
  host:
    - python
    - swig
    - pkg-config
    - gsl
    - numpy {{ numpy }}
    - pip
    - setuptools
  run:
    - python
    - gsl

test:
  imports:
    - pygsl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pygsl/pygsl
  summary: pygsl - GNU Scientific Library Interface
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - steffengraber
    - a093130
