{% set name = "pygsl" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pygsl/pygsl/releases/download/v{{ version }}/pygsl-{{ version }}.tar.gz
  sha256: a6935cfbdd1ee7d23858ec1a38d33928f643718299e7dca18bb158cdd596eb57

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2
  skip: true  # [win or py<38]

requirements:
  build:
    - python
    - {{ compiler('cxx') }}  [linux]
    - clangxx <=13  # [osx or arm64]
    - {{ stdlib("c") }}
  host:
    - python
    - cython
    - libcblas
    - setuptools
    - wheel
    - numpy >=1.8.2
    - pip
    - gsl
  run:
    - python 
    - gsl
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pygsl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pygsl/pygsl
  summary: pygsl - GNU Scientific Library Interface
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - steffengraber
